markdown: kramdown
title: "#YoMeCorono con T-share"
description: Súmate al reto por un mundo sin COVID-19 
slogan: Vestir es compartir
logo: 'assets/img/logo.png'
logo-white: 'assets/img/logo-white.png'
url: "https://marvlm.github.io"
baseurl: "/concurso-t-share/"
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - sections
include: ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
google_analytics: "UA-162940411-2"
formulario_inscripcion: "https://forms.gle/EZw7BZvYTepmWj8SA"
author: Marvin López
email: hola@t-share.es
blog: "https://tshare.digitalpress.blog/"
recursos: "https://drive.google.com/drive/folders/1OhO1q1zb0z1UcxzZwHXYm2nghyHuuh92?usp=sharing"
facebook: 
twitter: 
linkedin: "@tsharestore"
instagram: 
author_url: https://about.me/marvlm